# Generated by Django 4.0.3 on 2022-04-17 23:12

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('albergue', '0002_vacuna_alter_mascota_vacunas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='mascota',
            name='vacunas',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('parvovirus', 'Parvovirus'), ('moquillo', 'Moquillo'), ('hepatitis', 'Hepatitis'), ('adenovirus', 'Adenovirus'), ('rabia', 'Rabia'), ('herpesvirus', 'Herpesvirus'), ('calicivirus', 'Calicivirus')], max_length=70),
        ),
        migrations.AddField(
            model_name='mascota',
            name='sexo_mascota',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='albergue.sexo'),
        ),
    ]
