# Generated by Django 4.0.3 on 2022-04-20 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albergue', '0003_sexo_alter_mascota_vacunas_mascota_sexo_mascota'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adopcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=8)),
                ('direccion', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('nombre_mascota', models.CharField(max_length=40)),
                ('estado', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Adopcion',
                'verbose_name_plural': 'Adopciones',
            },
        ),
    ]
