# Generated by Django 4.0.3 on 2022-04-11 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RefugiowebApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registro',
            options={'verbose_name': 'registro', 'verbose_name_plural': 'registros'},
        ),
    ]
