# Generated by Django 4.0.3 on 2022-04-17 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RefugiowebApp', '0002_alter_registro_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Telefono', models.CharField(max_length=8)),
                ('Direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('Mascota', models.CharField(blank=True, max_length=40, null=True)),
                ('Ocupacion', models.CharField(blank=True, max_length=50, null=True)),
                ('Edad_de_mascota', models.CharField(blank=True, max_length=20, null=True)),
                ('Fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Registro',
        ),
    ]
