# Generated by Django 4.0.3 on 2022-04-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RefugiowebApp', '0003_datos_delete_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos',
            name='Foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
