# Generated by Django 4.0.3 on 2022-04-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RefugiowebApp', '0004_datos_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='Foto',
            field=models.ImageField(blank=True, null=True, upload_to='datos'),
        ),
    ]
